# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Hosted VS2017
  demands:
  - msbuild
  - cmake

steps:

- script: |
    git submodule sync --recursive
    git submodule update --init --recursive
    cmake -G "Visual Studio 15 2017 Win64" -DGRPC_AS_SUBMODULE=ON -DgRPC_BUILD_TESTS=OFF -B$(Build.BinariesDirectory) -DCMAKE_INSTALL_PREFIX=install
    cmake --build $(Build.BinariesDirectory) --target install
  displayName: 'Checkout and build'

# - task: CopyFiles@2
#   inputs:
#     sourceFolder: $(Build.BinariesDirectory)
#     contents: 'Debug/**'
#     targetFolder: $(Build.ArtifactStagingDirectory)

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/Debug/install/test1' 
    #includeRootFolder: true 
    archiveType: 'zip' # Options: zip, 7z, tar, wim
    #tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
    archiveFile: '$(Build.ArtifactStagingDirectory)/test-$(Build.BuildId).zip' 
    #replaceExistingArchive: true 
    #verbose: # Optional
    #quiet: # Optional

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: MyBuildOutputs
