# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Hosted VS2017
  demands:
  - msbuild
  - cmake

steps:

- script: |
    git submodule sync --recursive
    git submodule update --init --recursive
    cmake -G "Visual Studio 15 2017 Win64" -DGRPC_AS_SUBMODULE=ON -DgRPC_BUILD_TESTS=OFF -B$(Build.BinariesDirectory)
    cmake --build $(Build.BinariesDirectory)
  displayName: 'Checkout and build'

- task: CopyFiles@2
  inputs:
    contents: '$(Build.BinariesDirectory)/Debug/**'
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: MyBuildOutputs
