# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Hosted VS2017
  demands:
  - msbuild
  - cmake

steps:

- script: |
    git submodule sync --recursive
    git submodule update --init --recursive
  displayName: 'Checkout'

- task: CMake@1
  inputs:
    workingDirectory: 'build'
    cmakeArgs:  -G "Visual Studio 15 2017 Win64" -DGRPC_AS_SUBMODULE=ON -DgRPC_BUILD_TESTS=OFF -DBUILD_TESTING=OFF ..
  displayName: 'Build'

- task: CopyFiles@2
  inputs:
    sourceFolder: $(Build.BinariesDirectory)
    contents: 'Debug/**'
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: MyBuildOutputs
